version: "3"

services:
  mongo:
    image: mongo
    ports:
      - "$MONGO_CONTAINER_PORT:$MONGO_CONTAINER_PORT"
    environment:
      - MONGO_INITDB_DATABASE=$MONGO_DB
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
  api:
    image: challenge-verifymy
    container_name: challenge-verifymy
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - mongo
    ports:
      - "$API_PORT:$API_PORT"
    command: ["sh", "-c", "sleep 15 && ./main"]